CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT UNIQUE NOT NULL,
    balance DECIMAL(10, 2) NOT NULL DEFAULT 0
) ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS Tinkoff (
    id INT AUTO_INCREMENT UNIQUE NOT NULL,
    userId INT NOT NULL,
    amount INT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    paymentId INT,
    success BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (userId) REFERENCES Users (id)
) ENGINE=INNODB;


SELECT COUNT(*), COUNT(*)*100/(SELECT COUNT(*) FROM test_query)
FROM test_query
WHERE partnerSteamid64 = 4 AND state = 'Accept'
AND time between '2019-06-19 14:00' and '2019-06-19 15:00';
